{% set name = "gekko" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gekko-{{ version }}.tar.gz
  sha256: c5ce8d7cf0af904623506f3642616a0eebb4d9037029fa12e830e991d68c589f

build:
  noarch: python
  script:
    - rm -rf gekko/bin  # [not win] remove packaged files in sdist
    - rd /s /q "gekko\bin"  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.8

test:
  imports:
    - gekko
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BYU-PRISM/GEKKO
  summary: Machine learning and optimization for dynamic systems
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
